const fs = require('fs');
const path = require('path');

function getFiles(dir, allFiles = []) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      getFiles(filePath, allFiles);
    } else {
      allFiles.push(filePath);
    }
  }
  return allFiles;
}

const publicDir = path.join(__dirname, '..', 'public');
const files = getFiles(publicDir);
const map = {};

for (const f of files) {
  const ext = path.extname(f).toLowerCase();
  if (['.png', '.jpg', '.jpeg', '.webp', '.gif', '.svg', '.pdf'].includes(ext)) {
    const relative = path.relative(publicDir, f).replace(/\\/g, '/');
    const filename = path.basename(f);
    
    // Add exact match
    map[filename] = '/' + relative;
    // Add lowercase match for safety
    map[filename.toLowerCase()] = '/' + relative;
  }
}

const targetPath = path.join(__dirname, '..', 'src', 'utils', 'localImageMap.ts');
const fileContent = `// Automatically generated by scripts/build_image_map.cjs
// Do not edit this file directly.

export const localImageMap: Record<string, string> = ${JSON.stringify(map, null, 2)};
`;

fs.writeFileSync(targetPath, fileContent, 'utf8');
console.log('Successfully generated src/utils/localImageMap.ts');
